server:
  port: 8868

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Theembers/java-fun.git
          searchPaths: /env-config

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'