eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30 #续约到期时间(默认90秒)
    lease-renewal-interval-in-seconds: 10 #续约更新时间间隔(默认30秒)

spring:
  profiles: kafka
  kafka:
    bootstrap-servers: 192.168.0.211:9092,192.168.0.213:9092,192.168.0.218:9092